### ISSUE TITLE
Error display needs work

### ISSUE THREAD

**Issue by artlogic** [arsmentis/rusnack-pd#9]
A couple of issues:
* The length of an error should be limited - long lines are hard to read (fixed width #3 may resolve this)
* It's hard to tell when an error is long and wrapping vs, when it's a new error on the next line

**Comment by SKBruck** [comment]
Bootstrap has alert classes that make this stuff clear (rather than <p> tags), but I'm not sure how these would work with the tap and highlight necessity. I think it would be possible to combine tap and highlight styling to alert classes to maintain the need for those while simultaneously making it clear to users that they're being given actual error messages. I will code this for now and we can talk about it later.

**Comment by artlogic** [comment]
This actually works well. However, I'm thinking that there needs to be some indication that an error is click-able - right now it's a bit mysterious. Should I open a new issue, or should we keep working in this one?

**Comment by SKBruck** [comment]
Let's keep working in this one. I agree with your point, but I'm not certain the best way to indicate this for users, so it's going to take some thinking.

**Comment by artlogic** [comment]
You're using bootstrap alerts - right? Maybe a different color?

**Comment by SKBruck** [comment]
I am, yes. I'm not sure that a different color will tell mobile users that they can tap on them though.

**Comment by artlogic** [comment]
Maybe it's worth it to only highlight certain ones - regardless, think about it a bit and let me know what you come up with.

**Comment by artlogic** [comment]
The popover is good. I'm torn on the color. I'm starting to think maybe we need entirely different styling for non-clickable errors. What do you think?
